apiVersion: v1
kind: ConfigMap
metadata:
  name: startup-script
data:
  startup.sh: |
    #!/bin/sh
    set -e

    # Check curl install
    if ! command -v curl >/dev/null 2>&1; then
        echo "curl not found, try to install curl..."

        # Try apt-get(Debian/Ubuntu)
        if command -v apt-get >/dev/null 2>&1; then
            apt-get update && apt-get install -y curl
        # Try yum(CentOS/RHEL)
        elif command -v yum >/dev/null 2>&1; then
            yum install -y curl
        # Try apk(Alpine Linux)
        elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache curl
        else
            echo "Unable to find suitable package management tool and cannot install curl"
            tail -f /dev/null
            exit 1
        fi
    fi

    # Install code-server
    if curl -fsSL https://code-server.dev/install.sh | sh; then
        code-server --bind-addr 0.0.0.0:8777
    else
        tail -f /dev/null
    fi

