apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: {{ .Values.nfs.storageSize }}
  accessModes:
    - ReadWriteOnce
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}
  persistentVolumeReclaimPolicy: Recycle
