apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/wei-juncheng/dev_pod.git'
        revision: 'main'
        directories:
          - path: "charts/*"
        requeueAfterSeconds: 20 # Checks for changes every 20sec (default 3min)
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/wei-juncheng/dev_pod.git'
        targetRevision: 'main'
        chart: '{{path.basename}}'
        helm:
          values: |
            {{values | toYaml | indent 2}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
