apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helm-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/wei-juncheng/dev_pod.git'
        revision: main
        files:
          - path: "env-configs/*.yaml"
        requeueAfterSeconds: 20 # Checks for changes every 20sec (default 3min)
  template:
    metadata:
      name: '{{path.basename}}-{{ namespace }}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
      source:
        repoURL: 'https://github.com/wei-juncheng/dev_pod'
        path: charts/dev-pod
        targetRevision: HEAD
        helm:
          valueFiles:
          - values.yaml
          parameters:
          - name: replicaCount
            value: '{{ replicaCount }}'
          - name: image.repository
            value: '{{ components.dev_env.image.repository }}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: argocd
